name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '18'  # You can adjust this if needed

      # Change directory if package.json is not in the root
      - name: Install dependencies
        run: npm install
        working-directory: ./app # Modify path if necessary

      - name: Run tests
        run: npm test
        working-directory: ./app # Modify path if necessary
